"""migration

Revision ID: 07054327a518
Revises: db92074aa423
Create Date: 2024-11-11 12:04:11.527686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07054327a518'
down_revision: Union[str, None] = 'db92074aa423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_operations_time', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_operations_time', 'priority')
    # ### end Alembic commands ###
