"""migration

Revision ID: 9cb6bb723f85
Revises: 
Create Date: 2024-11-06 14:23:40.643423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb6bb723f85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('business_number', sa.String(), nullable=True))
    op.add_column('restaurant', sa.Column('restaurant_name', sa.String(), nullable=True))
    op.add_column('restaurant', sa.Column('url_slug', sa.String(), nullable=True))
    op.drop_constraint('restaurant_businessNumber_key', 'restaurant', type_='unique')
    op.drop_constraint('restaurant_restaurantName_key', 'restaurant', type_='unique')
    op.drop_constraint('restaurant_urlSlug_key', 'restaurant', type_='unique')
    op.create_unique_constraint(None, 'restaurant', ['url_slug'])
    op.create_unique_constraint(None, 'restaurant', ['business_number'])
    op.create_unique_constraint(None, 'restaurant', ['restaurant_name'])
    op.drop_column('restaurant', 'restaurantName')
    op.drop_column('restaurant', 'urlSlug')
    op.drop_column('restaurant', 'businessNumber')
    op.add_column('restaurant_address', sa.Column('house_number', sa.String(), nullable=True))
    op.drop_column('restaurant_address', 'houseNumber')
    op.add_column('restaurant_images', sa.Column('cover_photo', sa.String(), nullable=True))
    op.drop_column('restaurant_images', 'coverPhoto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_images', sa.Column('coverPhoto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('restaurant_images', 'cover_photo')
    op.add_column('restaurant_address', sa.Column('houseNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('restaurant_address', 'house_number')
    op.add_column('restaurant', sa.Column('businessNumber', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('restaurant', sa.Column('urlSlug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('restaurant', sa.Column('restaurantName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.create_unique_constraint('restaurant_urlSlug_key', 'restaurant', ['urlSlug'])
    op.create_unique_constraint('restaurant_restaurantName_key', 'restaurant', ['restaurantName'])
    op.create_unique_constraint('restaurant_businessNumber_key', 'restaurant', ['businessNumber'])
    op.drop_column('restaurant', 'url_slug')
    op.drop_column('restaurant', 'restaurant_name')
    op.drop_column('restaurant', 'business_number')
    # ### end Alembic commands ###
