"""migration

Revision ID: ca9e70d85953
Revises: f3da8e0593f2
Create Date: 2024-11-06 16:43:56.312851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9e70d85953'
down_revision: Union[str, None] = 'f3da8e0593f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurant_user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurant_user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
