"""migration

Revision ID: db92074aa423
Revises: ca9e70d85953
Create Date: 2024-11-07 13:55:42.066736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db92074aa423'
down_revision: Union[str, None] = 'ca9e70d85953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_user', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_user', 'image')
    # ### end Alembic commands ###
