"""migration

Revision ID: dceb7d297890
Revises: 07054327a518
Create Date: 2024-11-11 14:46:52.117131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dceb7d297890'
down_revision: Union[str, None] = '07054327a518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'restaurant_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'user_id')
    # ### end Alembic commands ###
