"""migration

Revision ID: f3da8e0593f2
Revises: 9cb6bb723f85
Create Date: 2024-11-06 14:25:07.371061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3da8e0593f2'
down_revision: Union[str, None] = '9cb6bb723f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'business_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurant', 'restaurant_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurant', 'url_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'url_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurant', 'restaurant_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurant', 'business_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
